// THIS FILE IS AUTOGENERATED BY create_flow_accounts.sh
// Contains actual account addresses from flow.json for use in Cadence tests.


let 0xAdmin: Address = 0xe2f72218abeec2b9
let 0xUserOne: Address = 0x06909bc5ba14c266
let 0xReceiver: Address = 0x10c4fef62310c807

// let admin = Test.getAccount(AdminAccountAddress)
